// Shared therapist database (used across all pages)
const therapists = [
    {
        id: 1,
        name: "Dr. Sarah Wanjiku",
        title: "Clinical Psychologist",
        specialties: ["Anxiety", "Depression", "Trauma", "Stress"],
        location: "nairobi",
        gender: "female",
        experience: 12,
        rating: 4.9,
        reviewCount: 128,
        bio: "Specializes in helping teens and young adults navigate anxiety, depression, and life transitions.",
        image: "assets/images/therapists/sarah.jpg",
        languages: ["English", "Swahili"],
        availability: "In-person & Online",
        sessionFee: "KES 3,500 - 5,000",
        onlineStatus: "online",
        ageGroups: ["teen", "young", "adult"]
    },
    {
        id: 2,
        name: "Michael Otieno",
        title: "Counseling Psychologist",
        specialties: ["Adolescent", "Family", "Relationships", "Stress"],
        location: "kisumu",
        gender: "male",
        experience: 8,
        rating: 4.8,
        reviewCount: 94,
        bio: "Experienced in helping teenagers build resilience and navigate school stress.",
        image: "assets/images/therapists/michael.jpg",
        languages: ["English", "Swahili", "Luo"],
        availability: "In-person & Online",
        sessionFee: "KES 3,000 - 4,500",
        onlineStatus: "online",
        ageGroups: ["teen", "young"]
    },
    {
        id: 3,
        name: "Dr. Amina Hassan",
        title: "Psychiatrist",
        specialties: ["Trauma", "PTSD", "Anxiety", "Depression"],
        location: "mombasa",
        gender: "female",
        experience: 15,
        rating: 4.9,
        reviewCount: 203,
        bio: "Board-certified psychiatrist specializing in trauma-informed care.",
        image: "assets/images/therapists/amina.jpg",
        languages: ["English", "Swahili", "Arabic"],
        availability: "In-person only",
        sessionFee: "KES 5,000 - 7,000",
        onlineStatus: "busy",
        ageGroups: ["adult"]
    },
    {
        id: 4,
        name: "Grace Nderitu",
        title: "Family Therapist",
        specialties: ["Family", "Relationships", "Adolescent", "Self-esteem"],
        location: "online",
        gender: "female",
        experience: 10,
        rating: 4.9,
        reviewCount: 156,
        bio: "Specializes in family dynamics, parent-teen communication, and relationship issues.",
        image: "assets/images/therapists/grace.jpg",
        languages: ["English", "Swahili", "Kikuyu"],
        availability: "Online only",
        sessionFee: "KES 3,500 - 5,500",
        onlineStatus: "online",
        ageGroups: ["teen", "young", "adult", "family"]
    }
];